baseURL: https://katatunix.github.io
languageCode: en-us
title: Kata learns to code

theme: LoveIt
enableRobotsTXT: true

params:
  defaultTheme: dark
  dateFormat: January 02, 2006
  author:
    name: Nghia
  images: [ "/avatar.jpg" ]
  description: Welcome to my world - I talk to the wind
  header:
  home:
    profile:
      enable: true
      avatarURL: "/lambda.jpg"
      title: Welcome to my world
      subtitle: I talk to the wind
      typeit: true
      social: true
    posts:
      paginate: 10
  social:
    github: katatunix
    telegram: nghiaokgood
    email: katatunix@gmail.com
    facebook: katatunix
    stackoverflow: 2198705
    linkedin: nghia-bui-02323b56
    rss: true
  analytics:
    google:
      id: G-4ZNSVY89ZS
  footer:
    enable: true
    custom:
    hugo: true    
    copyright: true
    author: true
    since: 2008
  page:
    summaryLength: 2000
    comment:
      enable: true
      disqus:
        enable: true
        shortname: katatunix
      utterances:
        enable: false
        repo: katatunix/katatunix.github.io
        issueTerm: pathname
        label: Comment
        lightTheme: github-light
        darkTheme: github-dark
    share:
      enable: true
      Facebook: true
      Linkedin: true
      X: false
      Threads: false
      Line: false
      HackerNews: false
      Diaspora: false
      Weibo: false
      Whatsapp: false
    code:
      maxShownLines: 100
    math:
      enable: true
  search:
    enable: true
    type: lunr
  section:
    dateFormat: Jan 02
  list:
    dateFormat: Jan 02
  
menu:
  main:
    - name: Posts
      url: /posts
      weight: 1
    - name: Categories
      url: /categories
      weight: 2
    - name: Tags
      url: /tags
      weight: 3
    - name:
      pre: <i class='fab fa-github fa-fw'></i>
      url: https://github.com/katatunix/katatunix.github.io
      weight: 4

markup:
  highlight:
    noClasses: false
    lineNos: true

outputs:
  home: [ HTML, RSS, JSON ]
